### ISSUE TITLE
Option to close session (window) when a session is saved

### ISSUE THREAD

**Issue by p3lim** [woodruffw/SimpleSession#1]
Also, if it's the only window open, just empty it.

Maybe have it as a separate function, "Save and Clear" perhaps.

Nice package :+1:

**Comment by woodruffw** [comment]
Thank you!

This is something I could add, but it might be better suited to a compound keybinding (through something like [Chain of Command](https://packagecontrol.io/packages/Chain%20of%20Command)).

I've been considering adding a configuration file - when I do, I'll probably add a `clear_on_save` option that can be toggled to achieve this.

**Comment by p3lim** [comment]
I would like to have them as separate menu entries, it's probably not always something I'd want.

**Comment by woodruffw** [comment]
I've implemented your request in 96d5cb3 (tagged as 1.1.0) - it should be available on Package Control in a few hours.

Cheers,
William

**Comment by p3lim** [comment]
:+1:
