### ISSUE TITLE
Feature: Save new files

### ISSUE THREAD

**Issue by matrinox** [woodruffw/SimpleSession#2]
Often times I have a lot of new tabs open in a window besides project files. These new files contain WIP code, code to test in console, etc. It'd make a lot of sense to just save all tabs in the session. The same could go for any unsaved changes in files. In a way, SimpleSession could be like mini-projects in projects. I hope this isn't too much of a departure from the 'Simple' in 'SimpleSession'.

**Comment by woodruffw** [comment]
Those tabs should be saved as part of the session as long as their files exist somewhere on disk.

If they're just buffers, SimpleSession doesn't (currently) have a mechanism for saving them. I might be able to add one as blobs in the session files that get loaded into views, but I'd have to look into the ST API more.

Thanks for bringing this to my attention!

**Comment by matrinox** [comment]
If you do this, I'd pay money for it. If project manager is able to do it, maybe there's something there to learn from. Good luck!

**Comment by woodruffw** [comment]
Sorry, I've been very busy.

I implemented the request with a quick hack. This won't save unsaved changes to files on disk, as the ST API doesn't have a clean way to approach something like that. All other buffers that don't already exist on disk will be reproduced when the session is loaded.

I'll push this as a new version in a few moments.
